week7
Lidemy/mentor-program-5th-iris1020 pull request #9
Opened 2021-06-11 14:42 UTC by iris1020

我終於做完了，再麻煩助教批改了，謝謝助教辛苦了！

2021-06-12 09:28 UTC, cwc329 requested changes
基本功能沒有完成，
都做好之後再 tag 我。
我會再來看。

2021-06-12 09:28 UTC, cwc329 commented on homeworks/week7/hw1/index.js
> +
如果通過檢查要 alert 出填答的資訊，
這邊沒有做。

2021-06-12 15:58 UTC, cwc329 reviewed
基本功能都有達到，
不過 hw1 沒有 alert 出「其他」的答案。
hw2 點擊答案區塊會收起的行為很奇怪。

另外，
我不知道你有沒有安裝 eslint，
因為我看一些排版應該是不會通過我們目前的 eslint 設定，
我在 local 跑 eslint 也沒有通過。
我看你目前還是會有一些小錯誤，
還是安裝 eslint 從頭開始培養一些習慣。

2021-06-12 15:58 UTC, cwc329 commented on homeworks/week7/hw1/index.js
> +			alert(JSON.stringify(values))
這邊沒有 alert 出「其他」的回答。

2021-06-12 15:58 UTC, cwc329 commented on homeworks/week7/hw1/index.js
> +		const elements = document.querySelectorAll(".required")
elements 太籠統，
這邊會有更好的命名選擇。

2021-06-12 15:58 UTC, cwc329 commented on homeworks/week7/hw1/index.html
> +				<div class="input-block required hide-error">
直接用 required 當作 class name 不太好，
因為 html 已經有一個 attribute 是 required，
有混淆的可能，
可以用前綴或者後綴的方式區分。

2021-06-12 15:58 UTC, cwc329 commented on homeworks/week7/hw2/index.js
> +		element.classList.toggle("faq-item--hide")
這邊點擊問題的答案區塊也會收起答案，
這樣的操作有點奇怪。

2021-06-12 15:58 UTC, cwc329 commented on homeworks/week7/hw3/index.js
> +	{
我有點不確定你有沒有裝 eslint，
這邊的排版應該會被 eslint 擋下來。

如果沒有裝，
請 `npm install`，
然後用 `npx eslint homewords` 檢查目前所有檔案，
有錯誤的話就修正。

2021-06-12 15:58 UTC, cwc329 commented on homeworks/week7/hw3/index.js
> +		document.querySelector(".input-todo").value = " " /*讓東西新增完之後不會繼續留在框框中*/
space 和 empty string 是不同的，
這邊應該要用 empty string。

你這邊會出現只要新增第一個 todo，
接下來不用輸入連點就可以新增內容為 ` ` 的 todo。

2021-06-12 15:58 UTC, cwc329 commented on homeworks/week7/hw4.md
> +Event delegation （事件委派），是一種受惠於 Event Bubbling 而能減少監聽器數目的方法。
不是 event bubbling ，
而是 event flow。

2021-06-12 15:58 UTC, cwc329 commented on homeworks/week7/hw4.md
> +`event.stopPrpagation()`：停止事件傳遞。當事件發生時，會經過捕獲與冒泡階段，取消事件傳遞就是讓事件停止在某一個節點上。
不是讓 event 停留在某個 node，
而是讓 event flow 停在某個 node。

event 和 event flow 是不同的事情。

2021-06-12 15:58 UTC, cwc329 commented on homeworks/week7/hw1/index.js
> +			alert(JSON.stringify(values))
radio 的 value 不是畫面顯示的文字，
這點可以改善。

2021-06-12 15:58 UTC, merged

2021-06-14 03:17 UTC, iris1020 commented
謝謝助教!
我真的沒有裝到 Eslint。
昨天裝好了，也正在訂正作業，希望之後可以好好照著 Eslint 要求的格式去寫。
辛苦助教了!